### PR TITLE
Report 4XX and 3XX links as link errors

### LINKED ISSUE #16: small read buffer error with current ReadBufferSize
Certain links cause `fasthttp` to return `ErrSmallBuffer`

To reproduce:
```
echo "[AWS Console](https://console.aws.amazon.com/support/v1#/case/history)" > test.md
liche test.md
```

Output:
```
test.md
        ERROR   https://console.aws.amazon.com/support/v1#/case/history
                Error when reading response headers: small read buffer. Increase ReadBufferSize. Buffer size=4096, contents: "HTTP/1.1 200 OK\r\nServer: Server\r\nDate: Fri, 15 Feb 2019 13:30:23 GMT\r\nContent-Type: text/html;charset=UTF-8\r\nContent-Length: 1004\r\nConnection: keep-alive\r\nCache-Control: private\r\nExpires: Thu, 01 Jan "..........cloudfront"
```

Looks like [fasthttp](https://godoc.org/github.com/valyala/fasthttp#HostClient) has a setting `ReadBufferSize` which will need to be set.

### LINKED ISSUE #23: liche reports 404 links as OK
```
~/go/src/github.com/raviqqe/liche$ cat a.md
# Test
A [404](http://www.google.com/idontexist.md) link.
~/go/src/github.com/raviqqe/liche$ liche -v a.md 
a.md
        OK      http://www.google.com/idontexist.md
```

It's expected that a non-existing file fails the link verification.

### PR DESCRIPTION
**Pull request by adrcunha**
If a link points to a file that 4XXs or 5XXs, it should be treated as a failure. Most obvious case is a typo in a link leading to 404 when clicked.

Also deal with the "small read buffer" error, so all tests pass.

Fixes #16.
Fixes #23.

### CODE REVIEW

**Comment by adrcunha** [comment]
The CircleCI failures seem to be related to configuration written in Ruby, not to the Liche Go code:

```
Offenses:

Gemfile:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
source 'https://rubygems.org'
^
features/aruba.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
require 'aruba/cucumber'
^
rakefile.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
task :deps do
^
```

**Comment by adrcunha** [comment]
@raviqqe all tests pass, this PR is now ready for review.

**Comment by SvanBoxel** [comment]
Would love to see this implemented. What's needed for the review?

**Comment by raviqqe** [comment]
Thanks for your contribution and patience!

**Comment by SvanBoxel** [comment]
Thank you @raviqqe! Could you create a new tag/release so we can refer to that instead of master?

**Comment by raviqqe** [comment]
I released v0.2.0 just now!

**Pull request merged**
