### PR TITLE
Fix issue #25

### PR DESCRIPTION
**Pull request by dantonyuk**
I've got an error trying to install liche:

```bash
> go get -u github.com/raviqqe/liche
build github.com/raviqqe/liche: cannot load gopkg.in/russross/blackfriday.v2: cannot find module providing package gopkg.in/russross/blackfriday.v2
```

See issue #25 

This PR is supposed to fix it, work for me ;-)

### CODE REVIEW

**Comment by raelga** [comment]
@raviqqe can we merge this into master? 

Thanks!

**Comment by Alan-Cha** [comment]
I am also experiencing the same install problem.

**Comment by raviqqe** [comment]
Thanks for contribution! Sorry for delay!

**Comment by raelga** [comment]
Thanks!

**Pull request merged**
