### PR TITLE
adding note about requiring Go Modules

### PR DESCRIPTION
**Pull request by josehelps**
Ran into this, though it should be documented. Closes issue #26

### CODE REVIEW

**Comment by pirj** [comment]
Confirming, the fix works. I ran into this problem and had no idea what to do.
Running installer as:
```sh
GO111MODULE=on go get -u github.com/raviqqe/liche
```
worked on a macOS system with freshly installed `go` from homebrew.

**Comment by spier** [comment]
I can also confirm that the above fix works. 
Would be. great to get this info merged into the README to save others the trouble :)

**Comment by eguiraud** [comment]
Hi, please merge, this would have saved me some time :smile:

**Comment by raviqqe** [comment]
Thanks for your contribution! Sorry for delay!

**Pull request merged**
